
spring.mongodb.uri=mongodb://localhost:27017/fileshare

server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=https://thorough-gannet-25.clerk.accounts.dev
clerk.jwks-url=https://thorough-gannet-25.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=ZYALer0sI62gdgeuxdqmeU1D9hsNRc4G

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB

razorpay.key.id=rzp_test_us_ThiqX0sSPptVGB
razorpay.key.secret=TKsRS21ExxewR8I6eUhOG5hj